# Generated by Django 4.2.6 on 2023-10-15 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="H1BData",
            fields=[
                (
                    "case_number",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                (
                    "wage_rate_of_pay",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "wage_unit_of_pay",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
            ],
        ),
    ]
